core/urls.py
from django.urls import path
from .views import index, signup, activate, home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('inicio/', home, name='home'),
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    #path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate'), 
    path('cambiar-contraseña/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('cambiar-contraseña/hecho/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
]

intensivos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('intensivo/<slug:slug>/', views.participante_view, name='intensivo'),
    path('success/', views.registro_exitoso, name='success'),
    path('intensivo/<int:intensivo_id>/verificar_codigo_descuento/', views.verificar_codigo_descuento, name='verificar_codigo_descuento'),
    
]

steam/urls.py
# steam/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('videos/', include('videos.urls')),
    path('', include('suscripciones.urls')),
    path('administracion/', include('administracion.urls')),
    path('', include('intensivos.urls')),
    
    
    
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intensivos/models.py
from datetime import timezone, datetime

from django.db import models
from django.template.defaultfilters import slugify


class Intensivo(models.Model):
    nombre = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)
    lugar = models.CharField(max_length=100)
    primera_fecha_pago = models.DateField()
    segunda_fecha_pago = models.DateField()
    fecha_evento = models.DateField()
    precio_primera_fecha_solo = models.DecimalField(max_digits=10, decimal_places=2)
    precio_primera_fecha_pareja = models.DecimalField(max_digits=10, decimal_places=2)
    precio_segunda_fecha_solo = models.DecimalField(max_digits=10, decimal_places=2)
    precio_segunda_fecha_pareja = models.DecimalField(max_digits=10, decimal_places=2)
    precio_promocion = models.DecimalField(max_digits=10, decimal_places=2)
    precio_especial = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return self.nombre
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nombre)
        super().save(*args, **kwargs)

class Participante(models.Model):
    intensivo = models.ForeignKey(Intensivo, on_delete=models.CASCADE, related_name='participantes')
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    telefono = models.CharField(max_length=15)
    viene_en_pareja = models.BooleanField(default=False)
    nombre_pareja = models.CharField(max_length=100, blank=True, null=True)
    correo_pareja = models.EmailField(blank=True, null=True)
    telefono_pareja = models.CharField(max_length=15, blank=True, null=True)
    screenshot_pago = models.ImageField(upload_to='pagos/')
    codigo_qr = models.ImageField(upload_to='intensivo_qrcodes/', blank=True, null=True)
    codigo_qr_pareja = models.ImageField(upload_to='intensivo_qrcodes/', blank=True, null=True)
    
    def __str__(self):
        return self.nombre


class CodigoDescuento(models.Model):
    codigo = models.CharField(max_length=50, unique=True)
    intensivo = models.ForeignKey(Intensivo, on_delete=models.CASCADE, related_name='codigos_descuento')
    usos_maximos = models.IntegerField()
    usos_actuales = models.IntegerField(default=0)
    fecha_expiracion = models.DateField()
    precio_descuento = models.DecimalField(max_digits=10, decimal_places=2)

    def esta_vigente(self):
        return datetime.now().date() <= self.fecha_expiracion and self.usos_actuales < self.usos_maximos
    
    def __str__(self):
        return self.codigo

intensivos/forms.py
from django import forms
from .models import Participante, Intensivo, CodigoDescuento

class ParticipanteForm(forms.ModelForm):
    codigo_descuento = forms.CharField(required=False)

    class Meta:
        model = Participante
        fields = ['nombre', 'correo', 'telefono', 'viene_en_pareja', 'nombre_pareja', 'correo_pareja', 'telefono_pareja', 'screenshot_pago', 'codigo_descuento']

class IntensivoForm(forms.ModelForm):
    
    primera_fecha_pago = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    segunda_fecha_pago = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    fecha_evento = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = Intensivo
        fields = ['nombre', 'lugar', 'primera_fecha_pago', 'segunda_fecha_pago', 'fecha_evento', 'precio_primera_fecha_solo', 'precio_primera_fecha_pareja', 'precio_segunda_fecha_solo', 'precio_segunda_fecha_pareja', 'precio_promocion', 'precio_especial']


class CodigoDescuentoForm(forms.ModelForm):
    fecha_expiracion = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = CodigoDescuento
        fields = ['codigo', 'precio_descuento', 'fecha_expiracion', 'usos_maximos', 'intensivo']

intensivos/views.py
from django.shortcuts import render, redirect
from .forms import ParticipanteForm, IntensivoForm
from .models import Intensivo
from django.utils import timezone

from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site

from .models import Participante, Intensivo, CodigoDescuento
from .signals import crear_qr, crear_qr_pareja

from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from .pdf_generator import generar_pdf

from django.http import JsonResponse
from django.db.models import F
from django.shortcuts import get_object_or_404


def enviar_correo(participante, request, pdf):
    current_site = get_current_site(request)
    mail_subject = 'Confirmación de registro'
    message = render_to_string('intensivo/correo_plantilla_registro.html', {
        'participante': participante,
        'domain': current_site.domain,
    })
    email = EmailMessage(mail_subject, message, to=[participante.correo])
    email.content_subtype = "html"  # Establece el contenido del correo electrónico como HTML
    email.attach('codigo_qr.pdf', pdf, 'application/pdf')
    email.send()


def participante_view(request, slug):
    # Obtenemos el objeto Intensivo correspondiente al ID proporcionado
    intensivo = get_object_or_404(Intensivo, slug=slug)
    # Obtenemos la fecha actual
    fecha_actual = timezone.now().date()

    # Inicializamos la variable codigo_descuento a None
    codigo_descuento = None

    # Verificamos si el método de la solicitud es POST
    if request.method == 'POST':
        # Creamos una instancia del formulario con los datos enviados en la solicitud
        form = ParticipanteForm(request.POST, request.FILES)
        # Verificamos si el formulario es válido
        if form.is_valid():
            # Obtenemos el código de descuento del formulario
            codigo_ingresado = form.cleaned_data.get('codigo_descuento')
            # Verificamos si se ingresó un código de descuento
            if codigo_ingresado:
                try:
                    # Intentamos obtener el código de descuento del modelo CodigoDescuento
                    codigo = intensivo.codigos_descuento.get(codigo=codigo_ingresado)
                    # Verificamos si el código de descuento está vigente
                    if codigo.esta_vigente():
                        # Si el código de descuento está vigente, lo guardamos en la variable codigo_descuento
                        codigo_descuento = codigo
                        # Incrementamos el número de usos actuales del código de descuento
                        codigo.usos_actuales += 1
                        # Guardamos el código de descuento
                        codigo.save()
                except CodigoDescuento.DoesNotExist:
                    # Si el código de descuento no existe, no hacemos nada
                    pass

            # Creamos una instancia del modelo Participante con los datos del formulario
            participante = form.save(commit=False)
            # Asignamos el objeto Intensivo al participante
            participante.intensivo = intensivo
            # Guardamos el participante
            participante.save()

            # Genera el PDF y lo adjunta al correo electrónico.
            pdf = generar_pdf(participante, 'codigo_qr')
            enviar_correo(participante, request, pdf)

            if participante.viene_en_pareja:
                pareja = Participante(nombre=participante.nombre_pareja, correo=participante.correo_pareja, telefono=participante.telefono_pareja)
                crear_qr_pareja(pareja)
                pdf_pareja = generar_pdf(pareja, 'codigo_qr_pareja')
                enviar_correo(pareja, request, pdf_pareja)

            return redirect('success')
    else:
        form = ParticipanteForm()

    context = {
        'form': form,
        'intensivo': intensivo,
        'codigo_descuento': codigo_descuento,
        'mostrar_seccion_1': fecha_actual <= intensivo.primera_fecha_pago,
        'mostrar_seccion_2': fecha_actual <= intensivo.primera_fecha_pago,
        'mostrar_seccion_3': intensivo.primera_fecha_pago < fecha_actual <= intensivo.segunda_fecha_pago,
        'mostrar_seccion_4': intensivo.primera_fecha_pago < fecha_actual <= intensivo.segunda_fecha_pago,
    }

    return render(request, 'intensivo/registro_participante.html', context)


def registro_intensivo(request):
    if request.method == 'POST':
        form = IntensivoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = IntensivoForm()
    return render(request, 'intensivo/registro_intensivo.html', {'form': form})


def registro_exitoso(request):
    
    return render(request, 'intensivo/registro_participante_success.html')


def verificar_codigo_descuento(request, intensivo_id):
    codigo = request.GET.get('codigo', None)
    intensivo = Intensivo.objects.get(id=intensivo_id)
    try:
        codigo_descuento = intensivo.codigos_descuento.get(codigo=codigo)
        es_valido = codigo_descuento.esta_vigente()
        precio_descuento = codigo_descuento.precio_descuento if es_valido else None
    except CodigoDescuento.DoesNotExist:
        es_valido = False
        precio_descuento = None
    data = {
        'es_valido': es_valido,
        'precio_descuento': str(precio_descuento),
    }
    return JsonResponse(data)

templates/intensivo/correo_plantilla_registro.html
<!DOCTYPE html>
<html>
<head>
    <title>Correo de confirmación</title>
</head>
<body>
    <h2>Hola {{ participante.nombre }},</h2>
    <p>Hemos confirmado tu registro a nuestro intensivo.</p>
    <p>Este es tu pase de entrada a nuestro evento, no olvides llevarlo.</p>
</body>
</html>

templates/intensivo/registro_participante.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}Intensivo{% endblock titulo %}

{% block clasebody %}class="bg-gradient-primary"{% endblock clasebody %}

{% block content %}
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-intensivo-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1>Intensivo "{{intensivo.nombre}}"</h1><br>
                                <h1 class="h4 text-gray-900 mb-4">Registro de Participante</h1>
                            </div>
                            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

                            <form method="POST" enctype="multipart/form-data" class="form-group">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.nombre.label_tag }}
                                    <input type="text" class="form-control" id="{{ form.nombre.id_for_label }}" name="{{ form.nombre.html_name }}" value="{{ form.nombre.value|default_if_none:'' }}">
                                    {% if form.nombre.errors %}
                                        <div class="alert alert-danger">
                                            {{ form.nombre.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.correo.label_tag }}
                                    <input type="email" class="form-control" id="{{ form.correo.id_for_label }}" name="{{ form.correo.html_name }}" value="{{ form.correo.value|default_if_none:'' }}">
                                    {% if form.nombre.errors %}
                                        <div class="alert alert-danger">
                                            {{ form.nombre.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.telefono.label_tag }}
                                    <input type="text" class="form-control" id="{{ form.telefono.id_for_label }}" name="{{ form.telefono.html_name }}" value="{{ form.telefono.value|default_if_none:'' }}">
                                    {% if form.nombre.errors %}
                                        <div class="alert alert-danger">
                                            {{ form.nombre.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="{{ form.viene_en_pareja.id_for_label }}" name="{{ form.viene_en_pareja.html_name }}" value="{{ form.viene_en_pareja.value|default_if_none:'' }}">
                                    <label class="form-check-label" for="{{ form.viene_en_pareja.id_for_label }}">
                                        {{ form.viene_en_pareja.label }}
                                    </label>
                                </div>
                                <br>
                                <div class="form-group">
                                    {{ form.codigo_descuento.label_tag }}
                                    <input type="text" class="form-control" id="{{ form.codigo_descuento.id_for_label }}" name="{{ form.codigo_descuento.html_name }}" value="{{ form.codigo_descuento.value|default_if_none:'' }}">
                                    <div id="mensaje_codigo"></div>
                                </div>
                                
                                <div id="pareja_info" style="display:none;">
                                    <div class="form-group">
                                        {{ form.nombre_pareja.label_tag }}
                                        <input type="text" class="form-control" id="{{ form.nombre_pareja.id_for_label }}" name="{{ form.nombre_pareja.html_name }}" value="{{ form.nombre_pareja.value|default_if_none:'' }}">
                                    </div>
                                    <div class="form-group">
                                        {{ form.correo_pareja.label_tag }}
                                        <input type="email" class="form-control" id="{{ form.correo_pareja.id_for_label }}" name="{{ form.correo_pareja.html_name }}" value="{{ form.correo_pareja.value|default_if_none:'' }}">
                                    </div>
                                    <div class="form-group">
                                        {{ form.telefono_pareja.label_tag }}
                                        <input type="text" class="form-control" id="{{ form.telefono_pareja.id_for_label }}" name="{{ form.telefono_pareja.html_name }}" value="{{ form.telefono_pareja.value|default_if_none:'' }}">
                                    </div>
                                </div>
                                <br>
                                <br>
                                {% if mostrar_seccion_1 %}
                                    <div id="seccion_1" style="display: {% if not form.viene_en_pareja.value %}block{% else %}none{% endif %};">
                                    <h2>Primera Fecha de Pago Individual</h2>
                                    <p class="precio">El precio a pagar es: COP {% if codigo_descuento %}{{ codigo_descuento.precio_descuento }}{% else %}{{ intensivo.precio_primera_fecha_solo }}{% endif %}</p>
                                    <p><strong>Puedes transferir al Nequi: 3156284108 o a Transfiya 3223654576</strong></p>
                                    <p>Recuerda revisar todos tus datos antes de enviar y subir el comprobante de pago.</p>
                                    <br>
                                    </div>
                                {% endif %}
                                {% if mostrar_seccion_2 %}
                                <div id="seccion_2" style="display: {% if not form.viene_en_pareja.value %}block{% else %}none{% endif %};">
                                    <h2>Primera Fecha de Pago en Pareja</h2>
                                    <p>El precio a pagar es: COP {{ intensivo.precio_primera_fecha_pareja }}</p>
                                    <p><strong>Puedes transferir al Nequi: 3156284108 o a Transfiya 3223654576</strong></p>
                                    <p>Recuerda llenar los datos de tu pareja y revisar todos tus datos antes de enviar y subir el comprobante de pago.</p>
                                    <br>
                                </div>
                                
                                {% endif %}
                                {% if mostrar_seccion_3 %}
                                    <div id="seccion_3" style="display: {% if not form.viene_en_pareja.value %}block{% else %}none{% endif %};">
                                    <h2>Segunda Fecha de Pago Individual</h2>
                                    <p>El precio a pagar es: COP {% if codigo_descuento %}{{ codigo_descuento.precio_descuento }}{% else %}{{ intensivo.precio_segunda_fecha_solo }}{% endif %}</p>
                                    <p><strong>Puedes transferir al Nequi: 3156284108 o a Transfiya 3223654576</strong></p>
                                    <p>Recuerda revisar todos tus datos antes de enviar y subir el comprobante de pago.</p>
                                    <br>
                                    </div>
                                {% endif %}
                                
                                {% if mostrar_seccion_4 %}
                                <div id="seccion_4" style="display: {% if not form.viene_en_pareja.value %}block{% else %}none{% endif %};">
                                    <h2>Segunda Fecha de Pago en Pareja</h2>
                                    <p>El precio a pagar es: COP {{ intensivo.precio_segunda_fecha_pareja }}</p>
                                    <p><strong>Puedes transferir al Nequi: 3156284108 o a Transfiya 3223654576</strong></p>
                                    <p>Recuerda llenar los datos de tu pareja y revisar todos tus datos antes de enviar y subir el comprobante de pago.</p>
                                    <br>
                                </div>
                                {% endif %}
                                

                                <div class="form-group">
                                    {{ form.screenshot_pago.label_tag }}
                                    <input type="file" class="form-control-file" id="{{ form.screenshot_pago.id_for_label }}" name="{{ form.screenshot_pago.html_name }}" value="{{ form.screenshot_pago.value|default_if_none:'' }}">
                                    {% if form.nombre.errors %}
                                        <div class="alert alert-danger">
                                            {{ form.nombre.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                <button type="submit" class="btn btn-primary">Registrar</button>
                            </form>
                            
                            
                            
                            
                            <hr>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    

    <script>
        $(document).ready(function(){
            function mostrarSecciones() {
                if($('#id_viene_en_pareja').is(':checked')){
                    $('#pareja_info').fadeIn('slow');
                    if({{ mostrar_seccion_2|yesno:"true,false" }}){
                        $('#seccion_2').show();
                        $('#seccion_1').hide();
                    }
                    if({{ mostrar_seccion_4|yesno:"true,false" }}){
                        $('#seccion_4').show();
                        $('#seccion_3').hide();
                    }
                } else {
                    $('#pareja_info').fadeOut('slow');
                    if({{ mostrar_seccion_1|yesno:"true,false" }}){
                        $('#seccion_1').show();
                        $('#seccion_2').hide();
                    }
                    if({{ mostrar_seccion_3|yesno:"true,false" }}){
                        $('#seccion_3').show();
                        $('#seccion_4').hide();
                    }
                }
            }
        
            // Llama a la función cuando se carga la página
            mostrarSecciones();
        
            $('#id_viene_en_pareja').change(mostrarSecciones);

            function verificarCodigo() {
                var codigo = $('#id_codigo_descuento').val();
                var vieneEnPareja = $('#id_viene_en_pareja').is(':checked');
                if (codigo && !vieneEnPareja) {
                    $.ajax({
                        url: '/intensivo/' + {{ intensivo.id }} + '/verificar_codigo_descuento/',
                        data: {
                            'codigo': codigo
                        },
                        dataType: 'json',
                        success: function(data) {
                            if (data.es_valido) {
                                $('#mensaje_codigo').text('El código de descuento es válido.').css('color', 'green');
                                $('.precio').text(' Código de descuento válido, precio a pagar: COP ' + data.precio_descuento);
                            } else {
                                $('#mensaje_codigo').text('El código de descuento no es válido.').css('color', 'red');
                            }
                        }
                    });
                } else {
                    $('#mensaje_codigo').text('El código de descuento no es válido si vienes en pareja.').css('color', 'red');
                }
            }
        
            $('#id_codigo_descuento').change(verificarCodigo);
            $('#id_viene_en_pareja').change(verificarCodigo);
        });
        </script>
        
        
        
        
        
        
        
        
    
           
{% endblock content %}

templates/intensivo/registro_participante_success.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}Intensivo{% endblock titulo %}

{% block clasebody %}class="bg-gradient-primary"{% endblock clasebody %}

{% block content %}
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-intensivo-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1>Intensivo Duane y Aleja</h1><br>
                                <h1 class="h4 text-gray-900 mb-4">Registro de Participante</h1>
                            </div>
                            <h3>Registro Exitoso!</h3>
                            <br>
                            <h4>Revisa tu correo electrónico con la confirmación y tu QR de ingreso</h4>
                            <br>
                            <br>

                            <h4>Te esperamos para Bachatear</h4><br>
                            <h4>Recuerda llegar puntual :)</h4><br>

                            <a class=" btn btn-primary" href="{% url "index" %}">Salir</a>
                            
                            
                            
                            
                            <hr>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    

    <script>
        $(document).ready(function(){
            function mostrarSecciones() {
                if($('#id_viene_en_pareja').is(':checked')){
                    $('#pareja_info').fadeIn('slow');
                    if({{ mostrar_seccion_2|yesno:"true,false" }}){
                        $('#seccion_2').show();
                        $('#seccion_1').hide();
                    }
                    if({{ mostrar_seccion_4|yesno:"true,false" }}){
                        $('#seccion_4').show();
                        $('#seccion_3').hide();
                    }
                } else {
                    $('#pareja_info').fadeOut('slow');
                    if({{ mostrar_seccion_1|yesno:"true,false" }}){
                        $('#seccion_1').show();
                        $('#seccion_2').hide();
                    }
                    if({{ mostrar_seccion_3|yesno:"true,false" }}){
                        $('#seccion_3').show();
                        $('#seccion_4').hide();
                    }
                }
            }
        
            // Llama a la función cuando se carga la página
            mostrarSecciones();
        
            $('#id_viene_en_pareja').change(mostrarSecciones);
        });
        </script>
        
        
        
        
        
        
        
        
    
           
{% endblock content %}